### ISSUE TITLE
2021-03-16，最近几天一直提示登录出错，签到失败

### ISSUE THREAD

**Issue by wdy3334** [fakedon/checkin#14]
2021-03-16 05:28:23,615 - 等待20秒重试
38
2021-03-16 05:28:43,638 - 使用IP: ***
39
2021-03-16 05:28:47,623 - 登陆出错
40
Traceback (most recent call last):
41
  File "hostloc/hostloc.py", line 221, in hostloc_checkin_retry
42
    hostloc_checkin(account, strage='local', show_secret=show_secret)
43
  File "hostloc/hostloc.py", line 185, in hostloc_checkin
44
    raise LoginError("登陆出错")
45
LoginError: 登陆出错
46
2021-03-16 05:28:47,623 - 签到失败
47
2021-03-16 05:28:47,626 - ========= 今日任务完成 ==========

**Comment by fakedon** [comment]
抱歉了, 我这边没时间修改了
使用这个老哥的吧
https://github.com/inkuang/hostloc-auto-get-points
